name: Build BetterHealthBar3

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Cloner le dépôt
        uses: actions/checkout@v3

      - name: Installer Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Compiler avec Gradle
        run: ./gradlew build

      - name: Sauvegarder le .jar
        uses: actions/upload-artifact@v3
        with:
          name: BetterHealthBar3
          path: build/libs/*.jar
